version: '3'
services:
  omega_get:
    build:
      context: .
    working_dir: /home/pwn
    container_name: omega_get
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9009:9009"
    entrypoint: /etc/init.sh
