version: '3'
services:
  notepad:
    build:
      context: .
    working_dir: /home/web
    container_name: notepad
    ulimits:
      nproc: 65535
      core: 0
    cap_add:
      - SYS_PTRACE
    ports:
      - "8001:8001"
    entrypoint: /etc/init.sh
