version: '3'
services:
  redis:
    image: redis:5
    command: "redis-server /redis.conf"
    volumes:
      - "${PWD}/challenge/redis.conf:/redis.conf"
  app:
    build: .
    ports:
      - 8004:4567
