version: '3'
services:
  diylist:
    build:
      context: .
    working_dir: /home/pwn
    container_name: diylist
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9007:9007"
    entrypoint: /etc/init.sh
