version: '3'
services:
  hipwn:
    build:
      context: .
    working_dir: /home/pwn
    container_name: hipwn
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9010:9010"
    entrypoint: /etc/init.sh
