version: '3'
services:
  grimoire:
    build:
      context: .
    working_dir: /home/pwn
    restart: always
    container_name: grimoire
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9008:9008"
    entrypoint: /etc/init.sh
